### ISSUE TITLE
Cannot Save NPC

### ISSUE THREAD

**Issue by jarrodwhitley** [HarmlessKey/Shieldmaiden#176]
**Describe the bug**
I'm unable to save the NPC I'm creating. I get the error "Save failed couldn't save monster"

**To Reproduce**
1. go to add NPC
2. copy from existing creature
3. edit info
4. click save

**Screenshots**
<img width="1728" alt="image" src="https://github.com/HarmlessKey/HarmlessKey/assets/11711674/bf3bc7fc-fc4d-4f6e-9856-1d92a671038e">

**Screenshots of errors in the dev console**
<img width="1728" alt="image" src="https://github.com/HarmlessKey/HarmlessKey/assets/11711674/2d9ebf55-d536-4837-82f2-d92150c7afab">

**Desktop (please complete the following information):**
 - Safari OSX 16.4

**Comment by Lakeyzer** [comment]
This looks like an issue with the specific monster that you tried to copy, do you remember what monster it was?

**Comment by Lakeyzer** [comment]
It seems that somehow the two handed option of a versatile action had it's value set to undefined. Was this the SRD Lizardfolk you copied and then edited before saving, or did you copy your custom existing Lizardfolk Shaman? If it was the latter, could you provide the JSON of this NPC?
A quick solution is updating the damage type for the two hand option of the action roll and try saving again.

**Comment by jarrodwhitley** [comment]
It was a druid-JarrodOn Aug 22, 2023, at 2:12 AM, Key Roos ***@***.***> wrote:﻿
This looks like an issue with the specific monster that you tried to copy, do you remember what monster it was?

**Comment by jarrodwhitley** [comment]
I had tried to copy a Druid and basically just rename it to “lizardfolk shaman”. Before that I think I may have tried to copy a lizardfolk to create tougher version called “lizardfolk beefy boy” lmaoBut I thought those were two separate actions.-JarrodOn Aug 22, 2023, at 2:26 AM, Key Roos ***@***.***> wrote:﻿
It seems that somehow the two handed option of a versatile action had it's value set to undefined. Was this the SRD Lizardfolk you copied and then edited before saving, or did you copy your custom existing Lizardfolk Shaman? If it was the latter, could you provide the JSON of this NPC?
A quick solution is updating the damage type for the two hand option of the action roll and try saving again.

**Comment by HarmlessHarm** [comment]
This is good information! It seems there is an issue with the druid NPC (and maybe other versatile attack NPCs). We'll dive into this.
For the mean time, you can simply remove the attack that contains a versatile attack, and re-add it via the interface.
