### ISSUE TITLE
Dicecloud V2 Imports are widely broken

### ISSUE THREAD

**Issue by SVNaas** [HarmlessKey/Shieldmaiden#270]
**Describe the bug**
Shieldmaiden fails to correctly import hitpoints if the V2 sheet has visible Temporary hitpoints and only counts those. It is also currently failing to import stats as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create/Access a character on Dicecloud
2. Use the Library of Vexus library for the character (this shouldn't matter as the SRD is based on Vexus)
3. Use an ability or extension that makes Temp HP visible (not needed for the stat import to fail)
4. Attempt import/sync via extension in Chrome.

**Expected behaviour**
The character stats, skills and full HP, including temporary HP should have imported. Along with any other relevant data.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c50164b-6bf9-4334-b6c7-f497b2a1d997)

**Screenshots of errors in the dev console**
![image](https://github.com/user-attachments/assets/dbe8c8ab-5123-430a-a092-3d969d7b9999)
![image](https://github.com/user-attachments/assets/15dca2b4-3a73-46f2-a2da-424a0e2d8b04)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 127.0.6533.99

**Comment by Lakeyzer** [comment]
Hey @SVNaas thanks for your report. I've just tried to reproduce this, but I wasn't able, my DiceCloud character syncs correctly. Can you test if you have the same issue with [my character](https://dicecloud.com/character/uDqRTjXFgtDwJaq3n/Keyzer) and is it possible you share the link of a public character that isn't correctly syncing?

**Comment by SVNaas** [comment]
Loaded yours and it has the same issues:
![image](https://github.com/user-attachments/assets/2e94e563-bcb7-49e6-88fa-90109bc6a41c)
https://dicecloud.com/character/L3ZKq2A9kyDxEeuM3/Sylreyne-Talris

**Comment by Lakeyzer** [comment]
I think I found what's happening. If I am correct, you have "Swap ability scores and modifiers" turned on in your settings. When I do this I get the same problem. 
We're going to take look and see if we can resolve the problem, but as a work around you can temporarily turn it off and then sync your character.

**Comment by SVNaas** [comment]
That did resolve it, though I'm unsure if it's supposed to also be looking for anything below senses on Shieldmaiden. As that and nothing below that populates either. The side menu guide isn't really clear on what exactly it should be looking to pull.

**Comment by SVNaas** [comment]
Also not sure if it's planned but there doesn't seem to be a provision for if a player has multiclassed and might have more than one spell save.

**Comment by Lakeyzer** [comment]
An update of the extension has been [released](https://github.com/HarmlessKey/CharacterSync/releases/tag/0.8.0) that fixes this problem.
