### ISSUE TITLE
Damage roll modifier not added when doing a custom attack

### ISSUE THREAD

**Issue by grigorijtomczuk** [HarmlessKey/Shieldmaiden#288]
**Describe the bug**
When you log a custom attack roll in Encounter tracker, damage roll modifier, specified within the roll formula, is not added to the rolled damage sum. When predefined SRD characters action-attack, the modifier is applied though.

**To Reproduce**
1. Go to Encounter tracker
2. When it's a custom character's turn, navigate to Roll Attack
3. Specify a damage formula with a modifier (e.g. 1d6+3)
4. Roll the attack and see that no modifier was added

**Expected behavior**
Modifier specified is added.

**Screenshots**
<div>
<img width="244" alt="Screenshot 2024-10-18 at 2 07 21 AM" src="https://github.com/user-attachments/assets/d85b46e9-74c6-4d62-82e4-fadc3c2338c9">
<img width="187" alt="Screenshot 2024-10-18 at 2 06 56 AM" src="https://github.com/user-attachments/assets/8402980f-13ff-49d1-83fe-bbde0575abc0">
</div>

**Screenshots of errors in the dev console**
No errors.

**Desktop:**
 - OS: macOS
 - Browser: chrome
 - Version: 130.0.6723.59

**Comment by Lakeyzer** [comment]
We'll have a look at this tomorrow, thanks for your report!
